/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillingUnlockRouteImport } from './routes/billing.unlock'
import { Route as AuthenticatedVisitasRouteImport } from './routes/_authenticated.visitas'
import { Route as AuthenticatedVendedoresRouteImport } from './routes/_authenticated.vendedores'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated.portal'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated.pedidos'
import { Route as AuthenticatedOrcamentosRouteImport } from './routes/_authenticated.orcamentos'
import { Route as AuthenticatedIndustriasRouteImport } from './routes/_authenticated.industrias'
import { Route as AuthenticatedFunilRouteImport } from './routes/_authenticated.funil'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated.clientes'
import { Route as AuthenticatedCatalogoRouteImport } from './routes/_authenticated.catalogo'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated.assinatura'
import { Route as POrgSlugCatalogoRouteImport } from './routes/p.$orgSlug.catalogo'
import { Route as AuthenticatedPOrgSlugPortalRouteImport } from './routes/_authenticated.p.$orgSlug.portal'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingUnlockRoute = BillingUnlockRouteImport.update({
  id: '/billing/unlock',
  path: '/billing/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVisitasRoute = AuthenticatedVisitasRouteImport.update({
  id: '/visitas',
  path: '/visitas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVendedoresRoute = AuthenticatedVendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrcamentosRoute = AuthenticatedOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIndustriasRoute = AuthenticatedIndustriasRouteImport.update({
  id: '/industrias',
  path: '/industrias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFunilRoute = AuthenticatedFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCatalogoRoute = AuthenticatedCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const POrgSlugCatalogoRoute = POrgSlugCatalogoRouteImport.update({
  id: '/p/$orgSlug/catalogo',
  path: '/p/$orgSlug/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPOrgSlugPortalRoute =
  AuthenticatedPOrgSlugPortalRouteImport.update({
    id: '/p/$orgSlug/portal',
    path: '/p/$orgSlug/portal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/catalogo': typeof AuthenticatedCatalogoRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/funil': typeof AuthenticatedFunilRoute
  '/industrias': typeof AuthenticatedIndustriasRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/vendedores': typeof AuthenticatedVendedoresRoute
  '/visitas': typeof AuthenticatedVisitasRoute
  '/billing/unlock': typeof BillingUnlockRoute
  '/p/$orgSlug/catalogo': typeof POrgSlugCatalogoRoute
  '/p/$orgSlug/portal': typeof AuthenticatedPOrgSlugPortalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/catalogo': typeof AuthenticatedCatalogoRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/funil': typeof AuthenticatedFunilRoute
  '/industrias': typeof AuthenticatedIndustriasRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/vendedores': typeof AuthenticatedVendedoresRoute
  '/visitas': typeof AuthenticatedVisitasRoute
  '/billing/unlock': typeof BillingUnlockRoute
  '/p/$orgSlug/catalogo': typeof POrgSlugCatalogoRoute
  '/p/$orgSlug/portal': typeof AuthenticatedPOrgSlugPortalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRoute
  '/_authenticated/catalogo': typeof AuthenticatedCatalogoRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/funil': typeof AuthenticatedFunilRoute
  '/_authenticated/industrias': typeof AuthenticatedIndustriasRoute
  '/_authenticated/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/vendedores': typeof AuthenticatedVendedoresRoute
  '/_authenticated/visitas': typeof AuthenticatedVisitasRoute
  '/billing/unlock': typeof BillingUnlockRoute
  '/p/$orgSlug/catalogo': typeof POrgSlugCatalogoRoute
  '/_authenticated/p/$orgSlug/portal': typeof AuthenticatedPOrgSlugPortalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/landing'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/assinatura'
    | '/catalogo'
    | '/clientes'
    | '/dashboard'
    | '/funil'
    | '/industrias'
    | '/orcamentos'
    | '/pedidos'
    | '/portal'
    | '/vendedores'
    | '/visitas'
    | '/billing/unlock'
    | '/p/$orgSlug/catalogo'
    | '/p/$orgSlug/portal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/landing'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/assinatura'
    | '/catalogo'
    | '/clientes'
    | '/dashboard'
    | '/funil'
    | '/industrias'
    | '/orcamentos'
    | '/pedidos'
    | '/portal'
    | '/vendedores'
    | '/visitas'
    | '/billing/unlock'
    | '/p/$orgSlug/catalogo'
    | '/p/$orgSlug/portal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/landing'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/assinatura'
    | '/_authenticated/catalogo'
    | '/_authenticated/clientes'
    | '/_authenticated/dashboard'
    | '/_authenticated/funil'
    | '/_authenticated/industrias'
    | '/_authenticated/orcamentos'
    | '/_authenticated/pedidos'
    | '/_authenticated/portal'
    | '/_authenticated/vendedores'
    | '/_authenticated/visitas'
    | '/billing/unlock'
    | '/p/$orgSlug/catalogo'
    | '/_authenticated/p/$orgSlug/portal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  BillingUnlockRoute: typeof BillingUnlockRoute
  POrgSlugCatalogoRoute: typeof POrgSlugCatalogoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/unlock': {
      id: '/billing/unlock'
      path: '/billing/unlock'
      fullPath: '/billing/unlock'
      preLoaderRoute: typeof BillingUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/visitas': {
      id: '/_authenticated/visitas'
      path: '/visitas'
      fullPath: '/visitas'
      preLoaderRoute: typeof AuthenticatedVisitasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendedores': {
      id: '/_authenticated/vendedores'
      path: '/vendedores'
      fullPath: '/vendedores'
      preLoaderRoute: typeof AuthenticatedVendedoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orcamentos': {
      id: '/_authenticated/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AuthenticatedOrcamentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/industrias': {
      id: '/_authenticated/industrias'
      path: '/industrias'
      fullPath: '/industrias'
      preLoaderRoute: typeof AuthenticatedIndustriasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/funil': {
      id: '/_authenticated/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof AuthenticatedFunilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalogo': {
      id: '/_authenticated/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof AuthenticatedCatalogoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/p/$orgSlug/catalogo': {
      id: '/p/$orgSlug/catalogo'
      path: '/p/$orgSlug/catalogo'
      fullPath: '/p/$orgSlug/catalogo'
      preLoaderRoute: typeof POrgSlugCatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/p/$orgSlug/portal': {
      id: '/_authenticated/p/$orgSlug/portal'
      path: '/p/$orgSlug/portal'
      fullPath: '/p/$orgSlug/portal'
      preLoaderRoute: typeof AuthenticatedPOrgSlugPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRoute
  AuthenticatedCatalogoRoute: typeof AuthenticatedCatalogoRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFunilRoute: typeof AuthenticatedFunilRoute
  AuthenticatedIndustriasRoute: typeof AuthenticatedIndustriasRoute
  AuthenticatedOrcamentosRoute: typeof AuthenticatedOrcamentosRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedVendedoresRoute: typeof AuthenticatedVendedoresRoute
  AuthenticatedVisitasRoute: typeof AuthenticatedVisitasRoute
  AuthenticatedPOrgSlugPortalRoute: typeof AuthenticatedPOrgSlugPortalRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRoute,
  AuthenticatedCatalogoRoute: AuthenticatedCatalogoRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFunilRoute: AuthenticatedFunilRoute,
  AuthenticatedIndustriasRoute: AuthenticatedIndustriasRoute,
  AuthenticatedOrcamentosRoute: AuthenticatedOrcamentosRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedVendedoresRoute: AuthenticatedVendedoresRoute,
  AuthenticatedVisitasRoute: AuthenticatedVisitasRoute,
  AuthenticatedPOrgSlugPortalRoute: AuthenticatedPOrgSlugPortalRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  BillingUnlockRoute: BillingUnlockRoute,
  POrgSlugCatalogoRoute: POrgSlugCatalogoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
